### ISSUE TITLE
Commenting map kv-pairs

### ISSUE THREAD

**Issue by hlolli** [dotemacs/clojure-comment-dwim.el#1]
There's a bug it seems when commenting kv-pairs

```Clojure
{
  :a 1 |
  :b 2
}
```

comments to illeagal map structure (perhaps detect where ;; makes sense vs #_ ?)

```Clojure
{
  #_:a 1 |
  :b 2
}
```

and as another thing happens when I select a region

```Clojure
{
  |:a 1 |
  :b 2
}
```

```
Debugger entered--Lisp error: (wrong-number-of-arguments (2 . 3) 0)
  comment-region()
  (if (use-region-p) (comment-region) (progn (back-to-indentation) (cond ((looking-at "#_") (clojure-comment-dwim-leading-comment "#_")) ((looking-at ";;") (clojure-comment-dwim-leading-comment ";;")) (t (clojure-comment-dwim-trailing-comment-or-no-comment)))))
  clojure-comment-dwim()
  funcall-interactively(clojure-comment-dwim)
  call-interactively(clojure-comment-dwim nil nil)
  command-execute(clojure-comment-dwim)
```

Thanks for working on this! The commenting of clojure code has always annoyed me in emacs, where I so often prefer just to `#_` where it makes sense.

**Comment by dotemacs** [comment]
Hey @hlolli thanks for the feedback! 

I take it you used the code from `master` branch?

Because the code in `s-expressions-only` branch works correctly. As in, it comments out the region using `(comment ...)`.

Please try that branch and let me know what you think, thanks :)

**Comment by dotemacs** [comment]
The changes above have been merged into master.

I'll close it for now, but if you're still seeing, please re-open.

Thanks for the feedback.
